var tree = [
    {
        id: 19,
        Date: 0,
        Month: 0,
        name: "น้องหัวตั้ง",
        water: "10/3/2023",
    },
    {
        id: 9,
        Date: 0,
        Month: 0,
        name: "น้องนกฮูกจิ๋ว(2)",
        water: "10/3/2023",
    },
    {
        id: 34,
        Date: 0,
        name: "ลูกๆน้องก๊าบก๊าบ",
        water: '10/3/2023',
    },
    {
        id: 4,
        Date: 0,
        Month: 0,
        name: "น้องหยดน้ำ(2)",
        water: "10/3/2023",
    },
    {
        id: 8,
        Date: 0,
        Month: 0,
        name: "น้องมะพร้าว",
        water: "10/3/2023",
    },
    {
        id: 8,
        Date: 0,
        Month: 0,
        name: "น้องกาแฟ (ยืมรูปมะพร้าว)",
        water: "10/3/2023",
    },
    {
        id: 1,
        Date: 0,
        Month: 0,
        name: "น้องขนแมว",
        water: "5/3/2023",
    },
    {
        id: 3,
        Date: 0,
        Month: 0,
        name: "น้องขนแมวจิ๋ว",
        water: "12/3/2023",
    },
    {
        id: 11,
        Date: 0,
        Month: 0,
        name: "น้องกระรอก",
        water: "12/3/2023",
    },
    {
        id: 12,
        Date: 0,
        Month: 0,
        name: "น้องโบ๊ท",
        water: "12/3/2023",
    },
    {
        id: 13,
        Date: 0,
        Month: 0,
        name: "น้องปุกปุย",
        water: "12/3/2023",
    },
    {
        id: 21,
        Date: 0,
        name: "น้องแพนด้าาา",
        water: '13/3/2023',
    },
    {
        id: 22,
        Date: 0,
        name: "น้องสน",
        water: '13/3/2023',
    },
    {
        id: 23,
        Date: 0,
        name: "น้องบัว",
        water: '13/3/2023',
    },
    {
        id: 24,
        Date: 0,
        name: "น้องกุหลาบ",
        water: '13/3/2023',
    },

    {
        id: 20,
        Date: 0,
        Month: 0,
        name: "น้องหัวสั้น",
        water: "12/3/2023",
    },
    {
        id: 27,
        Date: 0,
        name: "น้องแอสโตร(4)",
        water: '13/3/2023',
    },
    {
        id: 29,
        Date: 0,
        name: "น้องขนแกะ(2)",
        water: '14/3/2023',
    },
    {
        id: 32,
        Date: 0,
        name: "น้องคนเล็กมาก",
        water: '14/3/2023',
    },
    {
        id: 14,
        Date: 0,
        Month: 0,
        name: "เขียวอ่อน",
        water: "14/3/2023",
    },
    {
        id: 16,
        Date: 0,
        Month: 0,
        name: "เขียวเข้ม",
        water: "14/3/2023",
    },
    {
        id: 15,
        Date: 0,
        Month: 0,
        name: "น้องยิม(2)",
        water: "14/3/2023",
    },
    {
        id: 18,
        Date: 0,
        Month: 0,
        name: "น้องด่าง",
        water: "14/3/2023",
    },

];
export default tree
