var tree = [
    {
        id: 19,
        Date: 0,
        Month: 0,
        name: "น้องหัวตั้ง",
        water: "10/4/2023",
    },
    {
        id: 9,
        Date: 0,
        Month: 0,
        name: "น้องนกฮูกจิ๋ว(2)",
        water: "10/4/2023",
    },
    {
        id: 34,
        Date: 0,
        name: "น้องก๊าบก๊าบ",
        water: '10/4/2023',
    },
    {
        id: 4,
        Date: 0,
        Month: 0,
        name: "น้องหยดน้ำ(2)",
        water: "12/4/2023",
    },
    {
        id: 8,
        Date: 0,
        Month: 0,
        name: "น้องมะพร้าว",
        water: "12/4/2023",
    },
    {
        id: 39,
        Date: 0,
        Month: 0,
        name: "น้องกาแฟ",
        water: "12/4/2023",
    },
    {
        id: 1,
        Date: 0,
        Month: 0,
        name: "น้องขนแมว",
        water: "10/4/2023",
    },
    {
        id: 3,
        Date: 0,
        Month: 0,
        name: "น้องขนแมวจิ๋ว",
        water: "10/4/2023",
    },
    {
        id: 12,
        Date: 0,
        Month: 0,
        name: "น้องโบ๊ท",
        water: "10/4/2023",
    },
    {
        id: 13,
        Date: 0,
        Month: 0,
        name: "น้องปุกปุย",
        water: "10/4/2023",
    },
    {
        id: 20,
        Date: 0,
        Month: 0,
        name: "น้องหัวสั้น",
        water: "10/4/2023",
    },
    {
        id: 21,
        Date: 0,
        name: "น้องแพนด้าาา",
        water: '11/4/2023',
    },
    {
        id: 22,
        Date: 0,
        name: "น้องสน",
        water: '11/4/2023',
    },
    {
        id: 23,
        Date: 0,
        name: "น้องบัว",
        water: '11/4/2023',
    },
    {
        id: 24,
        Date: 0,
        name: "น้องกุหลาบ",
        water: '11/4/2023',
    },
    {
        id: 27,
        Date: 0,
        name: "น้องแอสโตร(4)",
        water: '11/4/2023',
    },
    {
        id: 29,
        Date: 0,
        name: "น้องขนแกะ",
        water: '12/4/2023',
    },
    {
        id: 15,
        Date: 0,
        Month: 0,
        name: "น้องยิม",
        water: "12/4/2023",
    },
    {
        id: 18,
        Date: 0,
        Month: 0,
        name: "น้องด่าง",
        water: "12/4/2023",
    },
     {
        id: 40,
        Date: 0,
        Month: 0,
        name: "น้องใบขน",
        water: "17/4/2023",
    },
     {
        id: 41,
        Date: 0,
        Month: 0,
        name: "น้องบอระเพรช",
        water: "17/4/2023",
    },

];
export default tree
