
    var tree = [
        {
          id: 1,
          Date: 0,
          Month: 0,
          name: "น้องขนแมว(2)",
          water: "31/12/2022",
        },
        {
          id: 3,
          Date: 0,
          Month: 0,
          name: "น้องขนแมวจิ๋ว",
          water: "1/1/2023",
        },
    
        {
          id: 4,
          Date: 0,
          Month: 0,
          name: "น้องหยดน้ำ(2)",
          water: "28/12/2022",
        },
        {
          id: 8,
          Date: 0,
          Month: 0,
          name: "น้องมะพร้าว",
          water: "1/1/2023",
        },
    
        {
          id: 9,
          Date: 0,
          Month: 0,
          name: "น้องนกฮูกจิ๋ว(2)",
          water: "5/1/2023",
        },
        {
          id: 11,
          Date: 0,
          Month: 0,
          name: "น้องกระรอก",
          water: "31/12/2022",
        },
    
        {
          id: 12,
          Date: 0,
          Month: 0,
          name: "น้องโบ๊ท",
          water: "31/12/2022",
        },
    
        {
          id: 13,
          Date: 0,
          Month: 0,
          name: "น้องปุกปุย",
          water: "31/12/2022",
        },
        {
          id: 14,
          Date: 0,
          Month: 0,
          name: "เขียวอ่อน",
          water: "3/1/2023",
        },
        {
          id: 16,
          Date: 0,
          Month: 0,
          name: "น้องยิม",
          water: "1/1/2023",
        },
        {
          id: 15,
          Date: 0,
          Month: 0,
          name: "เขียวเข้ม",
          water: "3/1/2023",
        },
        {
          id: 17,
          Date: 0,
          Month: 0,
          name: "น้องยิม",
          water: "1/1/2023",
        },
        {
          id: 18,
          Date: 0,
          Month: 0,
          name: "น้องด่าง",
          water: "3/1/2023",
        },
        {
          id: 19,
          Date: 0,
          Month: 0,
          name: "น้องหัวตั้ง",
          water: "5/1/2023",
        },
        {
          id: 20,
          Date: 0,
          Month: 0,
          name: "น้องหัวสั้น",
          water: "3/1/2023",
        },
        {
          id:21,
          Date:0,
          name:"น้องแพนด้าาา",
          water:'1/1/2023',
        },
        {
          id:22,
          Date:0,
          name:"น้องสน",
          water:'1/1/2023',
        },
        {
          id:23,
          Date:0,
          name:"น้องบัว",
          water:'1/1/2023',
        },
        {
          id:24,
          Date:0,
          name:"น้องกุหลาบ",
          water:'1/1/2023',
        },
        {
          id:27,
          Date:0,
          name:"น้องแอสโตร(4)",
          water:'3/1/2023',
        },
        {
          id:29,
          Date:0,
          name:"น้องขนแกะ(2)",
          water:'1/1/2023',
        },
        {
          id:32,
          Date:0,
          name:"น้องคนเล็กมาก",
          water:'3/1/2023',
        },
        {
          id:34,
          Date:0,
          name:"ลูกๆน้องก๊าบก๊าบ",
          water:'5/1/2023',
        },
      ];
export default tree
